version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - tascal-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    develop:
      watch:
        - action: sync
          path: ./backend
          target: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tascal-network

  db:
    image: postgres:15-alpine
    platform: linux/amd64
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always  # コンテナが停止した場合に自動的に再起動
    networks:
      - tascal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    platform: linux/amd64
    environment:
      - SWAGGER_JSON=/api/openapi.yaml
    ports:
      - "8080:8080"
    volumes:
      - ./api:/api
    develop:
      watch:
        - action: sync
          path: ./api
          target: /api
    depends_on:
      - backend
    networks:
      - tascal-network

volumes:
  db_data:

networks:
  tascal-network:
    driver: bridge