[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../../domain" }

sqlx = { version = "0.8.2", features = ["postgres", "runtime-tokio-rustls"] }
anyhow = "1.0.95"
async-trait = "0.1.83"
log = "0.4.22"
env_logger = "0.11.6"
