/* tslint:disable */
/* eslint-disable */
/**
 * 業務割当API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TaskStatus } from './task-status';

/**
 * 
 * @export
 * @interface TasksGetRequest
 */
export interface TasksGetRequest {
    /**
     * 
     * @type {string}
     * @memberof TasksGetRequest
     */
    'queryType': TasksGetRequestQueryTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof TasksGetRequest
     */
    'idList'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TasksGetRequest
     */
    'assignee'?: string;
    /**
     * 
     * @type {TaskStatus}
     * @memberof TasksGetRequest
     */
    'status'?: TaskStatus;
}

export const TasksGetRequestQueryTypeEnum = {
    IdList: 'IdList',
    Assignee: 'Assignee',
    Status: 'Status'
} as const;

export type TasksGetRequestQueryTypeEnum = typeof TasksGetRequestQueryTypeEnum[keyof typeof TasksGetRequestQueryTypeEnum];


