/* tslint:disable */
/* eslint-disable */
/**
 * Tascal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TaskStatus } from './task-status';

/**
 * 
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * タスクID
     * @type {string}
     * @memberof Task
     */
    'id'?: string;
    /**
     * タスクのタイトル
     * @type {string}
     * @memberof Task
     */
    'title': string;
    /**
     * タスクの詳細な説明
     * @type {string}
     * @memberof Task
     */
    'description'?: string;
    /**
     * 担当者
     * @type {string}
     * @memberof Task
     */
    'assignee'?: string;
    /**
     * 
     * @type {TaskStatus}
     * @memberof Task
     */
    'status': TaskStatus;
}



