/* tslint:disable */
/* eslint-disable */
/**
 * 業務割当API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TasksGet200ResponseInner
 */
export interface TasksGet200ResponseInner {
    /**
     * 
     * @type {number}
     * @memberof TasksGet200ResponseInner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof TasksGet200ResponseInner
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof TasksGet200ResponseInner
     */
    'assignee'?: string;
}

