/* tslint:disable */
/* eslint-disable */
/**
 * 業務割当API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * タスクID
     * @type {string}
     * @memberof Task
     */
    'id'?: string;
    /**
     * タスクのタイトル
     * @type {string}
     * @memberof Task
     */
    'title': string;
    /**
     * タスクの詳細な説明
     * @type {string}
     * @memberof Task
     */
    'description'?: string;
    /**
     * 担当者
     * @type {string}
     * @memberof Task
     */
    'assignee'?: string;
    /**
     * タスクの状態
     * @type {string}
     * @memberof Task
     */
    'status': TaskStatusEnum;
}

export const TaskStatusEnum = {
    Todo: 'todo',
    InProgress: 'in_progress',
    Done: 'done'
} as const;

export type TaskStatusEnum = typeof TaskStatusEnum[keyof typeof TaskStatusEnum];


