[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
openapi = { path = "../openapi" }

axum = "0.7.9"
axum-extra = "0.9.6"
tokio = { version = "1.42.0", features = ["full"] }
http = "1.2.0"
log = "0.4.22"
env_logger = "0.11.6"
anyhow = "1.0.95"
