openapi: 3.0.0
info:
  title: Tascal API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
paths:
  /health:
    get:
      summary: サーバーのヘルスチェック
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: string
  /tasks:
    get:
      summary: タスクの一覧を取得
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                queryType:
                  type: string
                  enum:
                    - IdList
                    - Assignee
                    - Status
                idList:
                  type: array
                  items:
                    type: string
                assignee:
                  type: string
                status:
                  $ref: "./components/schemas/TaskStatus.yaml"
              required:
                - queryType
                - queryValue
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./components/schemas/Task.yaml"
        "400":
          description: クエリが不正
          content:
            application/json:
              schema:
                type: string
    post:
      summary: タスクを新規作成
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./components/schemas/Task.yaml"
      responses:
        "201":
          description: 作成成功
          content:
            application/json:
              schema:
                $ref: "./components/schemas/Task.yaml"
