openapi: 3.0.0
info:
  title: 業務割当API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
components:
  schemas:
    Task:
      $ref: "./components/schemas/Task.yaml"
paths:
  /health:
    get:
      summary: サーバーのヘルスチェック
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: string
  /tasks:
    get:
      summary: タスクの一覧を取得
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                queryType:
                  type: string
                  enum:
                    - idList
                    - assignee
                    - status
                idList:
                  type: array
                  items:
                    type: string
                assignee:
                  type: string
                status:
                  type: string
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
    post:
      summary: タスクを新規作成
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: 作成成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
